// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "../src/App.bs.js";
import * as React from "react";
import * as Vitest from "rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";
import * as React$1 from "@testing-library/react";

Vitest.test("renders component without crashing", undefined, (function (t) {
        t.hasAssertions(1);
        React$1.render(React.createElement(App.make, {}));
        Vitest$1.expect(React$1.screen.getByText("Hello world!")).toBeInTheDocument();
        
      }));

export {
  
}
/*  Not a pure module */
