// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cell from "./Cell.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

import './App.css'
;

var initialState_guesses = [[]];

var initialState = {
  guesses: initialState_guesses,
  row: 0,
  col: 0,
  win: false
};

function reducer(state, action) {
  if (action._0 === "Enter") {
    return {
            guesses: state.guesses,
            row: state.row + 1 | 0,
            col: state.col,
            win: state.win
          };
  } else {
    return state;
  }
}

function App(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var handleKeyPress = React.useCallback((function (evt) {
          var key = evt.key;
          return Curry._1(dispatch, /* KeyPress */{
                      _0: key
                    });
        }), [dispatch]);
  return React.createElement("div", {
              onKeyPress: handleKeyPress
            }, React.createElement(Cell.make, {
                  character: undefined
                }));
}

var make = App;

export {
  initialState ,
  reducer ,
  make ,
  
}
/*  Not a pure module */
