// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css'
;

function Cell(Props) {
  var character = Props.character;
  if (character !== undefined) {
    return React.createElement("div", {
                className: "filled-cell"
              }, character);
  } else {
    return React.createElement("div", {
                className: "empty-cell"
              });
  }
}

var make = Cell;

export {
  make ,
  
}
/*  Not a pure module */
